### ISSUE TITLE
Issue on homepage (Cannot read property 'members' of undefined)

### ISSUE THREAD

**Issue by kanetjuh** [Disbotsxyz/Disbots#3]
After I set this up locally on my computer and on Glitch , I get the following error on the Home page
![image](https://user-images.githubusercontent.com/50002439/128565729-600d6455-fdb2-48ec-b44f-8e80f56cbcbf.png)

**Comment by Disbotsxyz** [comment]
Bro did you add server id in config?

**Comment by kanetjuh** [comment]
My bad, didn't saw the last few lines.
After testing, maintanance doesn't really work as it should! It's not possible to remove it...
![image](https://user-images.githubusercontent.com/50002439/128596383-32fe3b8e-12a5-46f8-a328-315ae6f2ee19.png)

**Comment by Disbotsxyz** [comment]
Bro maintenance mode has error so if you turn on maintenance it will show
redirect u many times, so go to mongodb and remove maintenance and if you
have any more questions pls join our discord server thankyou! Invite link:
https://discord.gg/ YhTU6Akzmy

**Comment by kanetjuh** [comment]
It worked before the changes where made 5 hours ago. (Github and Repl.it)
![image](https://user-images.githubusercontent.com/50002439/128600001-ab73cd2b-ab01-46ce-86b9-4a5f88b90c67.png)
![image](https://user-images.githubusercontent.com/50002439/128600325-557680ae-41e2-471e-9046-99aa94d5183d.png)

**Comment by Disbotsxyz** [comment]
Fixed.....
