### ISSUE TITLE
This isnt a issue more or less a suggestion a great idea brought by dislist team 

### ISSUE THREAD

**Issue by ghost** [Disbotsxyz/Disbots#8]
their should be on the left side bar or somewhere visible in the admin panel where bot testers may claim that bot to deal with the tests to not have staff running double tests on a bot causing some delay times in verification for some users bots! please also check the additions ive added

**Comment by djwalkzz16** [comment]
Can u explain more

**Comment by AndyIsHereBoi** [comment]
he means that they want a option where bot testers can claim bots to test (so there isnt 2 people testing it at once)
